### ISSUE TITLE
批量导入主机异常 Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by ericheroster** [openspug/spug#109]
![image](https://user-images.githubusercontent.com/250643/83851399-e2a06a80-a744-11ea-90f3-4ef1adc6de7b.png)

api.log

Traceback (most recent call last):
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/data/spug/spug_api/apps/host/views.py", line 121, in post_import
    if valid_ssh(data.hostname, data.port, data.username, data.pop('password') or password) is False:
  File "/data/spug/spug_api/apps/host/views.py", line 149, in valid_ssh
    chmod 600 ~/.ssh/authorized_keys' % public_key)
  File "/data/spug/spug_api/libs/ssh.py", line 60, in exec_command
    with self as cli:
  File "/data/spug/spug_api/libs/ssh.py", line 106, in __enter__
    return self.get_client()
  File "/data/spug/spug_api/libs/ssh.py", line 49, in get_client
    self.client.connect(**self.arguments)
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/client.py", line 406, in connect
    t.start_client(timeout=timeout)
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/transport.py", line 660, in start_client
    raise e
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/transport.py", line 2039, in run
    self._check_banner()
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/transport.py", line 2216, in _check_banner
    "Error reading SSH protocol banner" + str(e)
paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Exception: Error reading SSH protocol banner[Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/transport.py", line 2211, in _check_banner
    buf = self.packetizer.readline(timeout)
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/packet.py", line 380, in readline
    buf += self._read_timeout(timeout)
  File "/data/spug/spug_api/venv/lib64/python3.6/site-packages/paramiko/packet.py", line 607, in _read_timeout
    x = self.__socket.recv(128)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by vapao** [comment]
某个导入的主机无法连接， 你那里部署的哪个版本？

**Comment by ericheroster** [comment]
curl https://spug.dev/installer/spug-installer | bash 使用这个命令安装的最新版。
好的，我自己再检查下，我模板里面有好几十个主机，可能是你说的某导入主机无法连接导致的，还有系统错误提示信息是否可以再明确一点？

**Comment by vapao** [comment]
导入的异常情况很多，无法完全都捕获。看下你现在的版本如果是 2.3.0 建议升级至 2.3.1。

**Comment by vapao** [comment]
很久没收到回复先关闭问题了，有需要请再打开。
