### ISSUE TITLE
Bug: 新版zsh支持问题

### ISSUE THREAD

**Issue by czy** [openspug/spug#386]
Spug 版本: >= v3.0.1-beta.8

## 问题重现步骤

1. 使用v3.0.1-beta.7版本发布正常
2. 使用>=v3.0.1-beta.8版本发布报错

## 报错/问题截图
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python/3.9.5/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/python/3.9.5/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/git/spug/spug_api/apps/deploy/utils.py", line 54, in dispatch
    raise e
  File "/home/git/spug/spug_api/apps/deploy/utils.py", line 48, in dispatch
    _ext1_deploy(req, helper, env)
  File "/home/git/spug/spug_api/apps/deploy/utils.py", line 94, in _ext1_deploy
    raise latest_exception
  File "/usr/local/python/3.9.5/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/git/spug/spug_api/apps/deploy/utils.py", line 237, in _deploy_ext1_host
    helper.remote(host.id, ssh, command)
  File "/home/git/spug/spug_api/apps/deploy/helper.py", line 203, in remote
    for code, out in ssh.exec_command_with_stream(command, environment=env):
  File "/home/git/spug/spug_api/libs/ssh.py", line 101, in exec_command_with_stream
    channel = self._get_channel()
  File "/home/git/spug/spug_api/libs/ssh.py", line 152, in _get_channel
    raise Exception('Wait spug response timeout')
Exception: Wait spug response timeout

## 期望的结果
望修复ssh.py以支持zsh

**Comment by vapao** [comment]
你现在的版本是多少呢？  最新的已经优化过这个问题了。

**Comment by vapao** [comment]
已发布 v3.0.1-beta.13 可以测试验证下。

**Comment by czy** [comment]
> 
 还是同一个错误，只是出错行变了
![image](https://user-images.githubusercontent.com/1300315/142965393-2a206f95-7eec-4319-a32d-d10ff17acc8f.png)

Traceback (most recent call last):
  File "/usr/local/python/3.9.5/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/python/3.9.5/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/git/spug/spug_api/apps/deploy/utils.py", line 54, in dispatch
    raise e
  File "/home/git/spug/spug_api/apps/deploy/utils.py", line 48, in dispatch
    _ext1_deploy(req, helper, env)
  File "/home/git/spug/spug_api/apps/deploy/utils.py", line 101, in _ext1_deploy
    raise latest_exception
  File "/usr/local/python/3.9.5/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/git/spug/spug_api/apps/deploy/utils.py", line 244, in _deploy_ext1_host
    helper.remote(host.id, ssh, command)
  File "/home/git/spug/spug_api/apps/deploy/helper.py", line 250, in remote
    for code, out in ssh.exec_command_with_stream(command, environment=env):
  File "/home/git/spug/spug_api/libs/ssh.py", line 99, in exec_command_with_stream
    channel = self._get_channel()
  File "/home/git/spug/spug_api/libs/ssh.py", line 154, in _get_channel
    raise Exception('Wait spug response timeout')
Exception: Wait spug response timeout

**Comment by vapao** [comment]
这个问题能复现吗， 每次执行都会出现？  目标主机是什么操作系统 哪个版本？

**Comment by czy** [comment]
> 这个问题能复现吗， 每次执行都会出现？ 目标主机是什么操作系统 哪个版本？

每次必复现，目标主机是阿里云的CentOS系统：
CentOS Linux release 7.9.2009 (Core)
3.10.0-1160.45.1.el7.x86_64

ZSH版本：zsh 5.8 (x86_64-pc-linux-gnu)

**Comment by zyupo** [comment]
4.0 应该已解决。

3.0 下发的脚本用了 bash 专有语法，在 zsh/dash/ash 等登录 shell 下会出问题。4.0 已统一改为 POSIX sh 语法，并在多个发行版上做过实机验证。

如果在 4.0 上仍然复现，请重开并附上 shell 版本，我们再看。
