### ISSUE TITLE
python3.7.1安装python-ldap失败

### ISSUE THREAD

**Issue by baoming158** [openspug/spug#44]
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    from setuptools import setup, Extension
  File "/data/spug/spug_api/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/data/spug/spug_api/venv/lib/python3.7/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/data/spug/spug_api/venv/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

总是有依赖会安装失败，各种查，心累。

**Comment by vapao** [comment]
这个是Python 3.7 的问题，需要执行 `yum install libffi-devel` 后，重新编译安装即可。

**Comment by baoming158** [comment]
thanks It's all right now

**Comment by vapao** [comment]
使用中有什么问题，欢迎提交issue

**Comment by iceran** [comment]
window 上出现这个问题该怎么解决， python 同样是3.7的版本

**Comment by vapao** [comment]
可以发个完整的报错看下，推荐使用linux系统部署spug

**Comment by unixtommy** [comment]
我也遇到 ldap 开发环境装不上，mac环境，会影响后面二次开发吗
