### ISSUE TITLE
如何解禁不存在的用户

### ISSUE THREAD

**Issue by liuze0118** [openspug/spug#499]
选择LDAP登录，随意输入一个不存在的账户123，和密码 123 。多次登录之后提示该账账户已被系统禁用。怎么才能解除这种禁用

**Comment by vapao** [comment]
这种禁用状态在redis中，默认会保持1天。 我们已经改进了 enable 命令支持这种情况，下个版本更新，。

**Comment by vapao** [comment]
v3.1.6 已更新， 参考 https://spug.cc/docs/system-account 解禁账户。

**Comment by APTXOUS** [comment]
选择ldap登陆，第一次输入新用户，但是连续输错三次密码，无法使用下面的命令进行解禁
```
docker exec spug python3 /data/spug/spug_api/manage.py user enable -u admin
```
输出如下：
```
Traceback (most recent call last):
  File "/data/spug/spug_api/manage.py", line 24, in <module>
    main()
  File "/data/spug/spug_api/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/data/spug/spug_api/apps/account/management/commands/user.py", line 58, in handle
    cache.delete(user.username)
AttributeError: 'NoneType' object has no attribute 'username'
```
