### ISSUE TITLE
在应用列表里点击发布是有报错

### ISSUE THREAD

**Issue by zhutong7758** [openspug/spug#6]
--------------------------------------------------------------------------------
ERROR in middleware [/spug/spug_api/libs/middleware.py:40]:
'bool' object has no attribute 'lower'
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/spug/spug_api/libs/decorators.py", line 28, in wrapper
    return func(*args, **kwargs)
  File "/spug/spug_api/apps/deploy/publish.py", line 39, in app_update
    Argument('host_ids', type=list)
  File "/spug/spug_api/libs/tools.py", line 143, in parse
    rst[e.name] = e.parse(*self._get(e.name))
  File "/spug/spug_api/libs/tools.py", line 108, in parse
    assert value.lower in ['true', 'false']
AttributeError: 'bool' object has no attribute 'lower'

这是是我操作问题，还是bug呢

**Comment by vapao** [comment]
@zhutong7758 即将发布的1.0.1版本修复该问题
