### ISSUE TITLE
Bug: [windows]系统初始化错误，无法建立admin账户

### ISSUE THREAD

**Issue by DZG-MELODY** [openspug/spug#695]
Spug 版本:V3.3.3
操作系统:windows 11

## 问题重现步骤

启动镜像服务后，运行如下脚本：

```sh
docker exec spug init_spug admin spug.cc
```

## 报错/问题截图

No changes detected in apps 'repository', 'setting', 'schedule', 'monitor', 'alarm', 'app', 'notify', 'deploy', 'host', 'config', 'account', 'exec', 'home'
Operations to perform:
  Apply all migrations: account, alarm, app, config, deploy, exec, home, host, monitor, notify, repository, schedule, setting
Running migrations:
  Applying alarm.0001_initial... OK
  Applying config.0001_initial...Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)        
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/spug/spug_api/manage.py", line 24, in <module>
    main()
  File "/data/spug/spug_api/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 364, in execute 
    output = self.handle(*args, **options)
  File "/data/spug/spug_api/apps/account/management/commands/updatedb.py", line 16, in handle
    execute_from_command_line(['manage.py', 'migrate'])
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 364, in execute 
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/base.py", line 83, in wrapped  
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)  
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.10/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    with self.connection.schema_editor(atomic=migration.atomic) as schema_editor:
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 110, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute     
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_w  File "/usr/local/li  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/mysql/base.py", line 71, in execute    return self.cursor.execute(query, args)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 239, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2013, 'Lost connection to MySQL server during query')

**Comment by wanxiaoxiang** [comment]
同问

**Comment by ysicing** [comment]
连接数据库问题吧。

可以使用参考我们提供的镜像 [hub.qucheng.com/app/spug:3.3.3-20241217](https://github.com/quicklyon/spug-docker/blob/main/docker-compose.yml)

**Comment by zyupo** [comment]
这个看起来是初始化的时候数据库连接失败了。检查一下你的数据库配置

**Comment by LookUpPls** [comment]
image: mariadb:10.6.23   数据库换这个版本试试 ， 我的好了

**Comment by zyupo** [comment]
感谢当初的反馈，信息写得很完整——版本和复现步骤都有，是我们没能及时跟进。

这条记录的是 3.x，而 4.0 分支对发布、执行、主机管理等模块改动较大。想请你确认一下：**这个问题在 4.0 上是否还存在？**

演示环境 https://demo.spug.cc （admin / spug.cc）跑的就是 4.0，可以先在上面试试。

- 如果还复现，回一句，我们优先排；
- 如果 4.0 已经好了，也回一句，我们直接关掉。

两周内没有回应的话我们会先关闭，你随时可以重开。

**Comment by zyupo** [comment]
之前留言没有收到回复，先关闭。补充：这个报错是初始化建表时 MySQL 断开连接，通常是数据库容器没起好或版本兼容问题，楼上 @LookUpPls 换 `mariadb:10.6` 解决了；4.0 的 docker-compose 默认使用 `mariadb:10.8`，Windows Docker Desktop 上按官方文档部署即可：https://ops.spug.cc/docs/install-docker/

这条我们也会在 4.0 上再复核一遍，确认存在会修复并在这里更新。
