### ISSUE TITLE
docker启动持久化存储报错

### ISSUE THREAD

**Issue by ztommyc** [openspug/spug#78]
```
[tee@mtee-test01 opt]$ docker run -d -p 8888:80 -v /opt/spug:/data registry.aliyuncs.com/openspug/spug
cdae7174e79ee82d29cad304a6587956cb1df32701ffbb01babf9f484dd9313c
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/data/spug/spug_api\") set in config.json failed: no such file or directory".
```

`[tee@mtee-test01 opt]$ docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
registry.aliyuncs.com/openspug/spug   latest              2f4ab8437e2a        20 hours ago        555 MB
`

`
[tee@mtee-test01 opt]$ docker inspect 2f4ab8437e2a
[
    {
        "Id": "sha256:2f4ab8437e2a8362663efc57336db9ebaefe758cb863e4c28060cbf6081670d4",
        "RepoTags": [
            "registry.aliyuncs.com/openspug/spug:latest"
        ],
        "RepoDigests": [
            "registry.aliyuncs.com/openspug/spug@sha256:cfe78ebf841fc0003129ad527527ee99b37c82fb7a10b537e4691c2d65497784"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2020-05-18T07:20:30.349596131Z",
        "Container": "c01c0879e2164a40fd6e4f7a046b0779677f44902981a7385288608ec2732fe4",
        "ContainerConfig": {
            "Hostname": "c01c0879e216",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.6.10",
                "PYTHON_PIP_VERSION=20.1",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/1fe530e9e3d800be94e04f6428460fc4fb94f5a9/get-pip.py",
                "PYTHON_GET_PIP_SHA256=ce486cddac44e99496a702aa5c06c5028414ef48fdfd5242cd2fe559b13d4348",
                "TZ=Asia/Shanghai"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/entrypoint.sh\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:10c9a027344ef2e426759dbeaa00d06e9db81b846b173fe240d3e1fe4ebdc46b",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "/data/spug/spug_api",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "DockerVersion": "18.06.1-ce",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.6.10",
                "PYTHON_PIP_VERSION=20.1",
                "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/1fe530e9e3d800be94e04f6428460fc4fb94f5a9/get-pip.py",
                "PYTHON_GET_PIP_SHA256=ce486cddac44e99496a702aa5c06c5028414ef48fdfd5242cd2fe559b13d4348",
                "TZ=Asia/Shanghai"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "sha256:10c9a027344ef2e426759dbeaa00d06e9db81b846b173fe240d3e1fe4ebdc46b",
            "Volumes": {
                "/data": {}
            },
            "WorkingDir": "/data/spug/spug_api",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": null
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 555464268,
        "VirtualSize": 555464268,
        "GraphDriver": {
            "Name": "devicemapper",
            "Data": {
                "DeviceId": "15",
                "DeviceName": "docker-253:0-14016521-65cea5c90e59cc41efdde6ee1757b52c93edd4f875f69a54f21dd9b4ca698f90",
                "DeviceSize": "10737418240"
            }
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:3e207b409db364b595ba862cdc12be96dcdad8e36c59a03b7b3b61c946a5741a",
                "sha256:a539b76feca4479232b3e15c29bf441c080441900384376dac2b0d7ca210fb1f",
                "sha256:3cf06063a67d56e31d03c2858a0497c5fa02081b561cdf547a63bc54812d60a0",
                "sha256:e04b9655bf6d2251d8e584024ddfe33b84c9822f09fc7626ca01ba75b18277b0",
                "sha256:51d39d4fb618e1af04f2191d8df4d2c5315a1372ed7662af869e855f7b72f5c4",
                "sha256:f508856abfc90d23390b7d90bc855fe4e95cf5d25a122c9583d9de514bd402e0",
                "sha256:a5b32dd36854ef4de98c5b46fccb3e59cbda25385c433421367034cd6e58e366",
                "sha256:b96b14e82b3bfca32b9f264d418c812c4bb30028ccfaceef405ced0905af8df8",
                "sha256:45dfdb7210e4b90190a205dd11861214f4aadd1486718b7014b018aa860f3ffe",
                "sha256:69bb6c8baef076a61d261d7c278cae785c62c955e656009dc8ef1647a162aa5e",
                "sha256:2ea2cabfb4df4ec452e2ef1ab81d9fc0373c5561d9c0ef7ade5349f254486c24",
                "sha256:c8cc209aa23d8ddec27bf023cbd4044f432af5bf7aef1a64b1826e2edff1a3fb",
                "sha256:7033c178a57bbc830a0b17df4d57c2d509419ffd59917f5860198439df103a36",
                "sha256:5903873f798bc509030dadc42261da39956a6127e5e2706c438de69748b7d980"
            ]
        }
    }
]
`

**Comment by zyupo** [comment]
确认一下你本地/opt目录下面的spug目录是否存在。如果不存在就 -v /opt/:/data

**Comment by ztommyc** [comment]
目录存在:
```
[root@tee-test01 spug]# pwd
/opt/spug
[root@tee-test01 spug]# docker run -d -p 8888:80 -v /opt/spug:/data registry.aliyuncs.com/openspug/spug
71004257b6fba75962b505134650cf11550d9e64c08308279ccdd78260e4e375
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/data/spug/spug_api\") set in config.json failed: no such file or directory".
```

直接/opt/
```
[root@me-test01 spug]# cd ..
[root@me-test01 opt]# pwd
/opt
[root@me-test01 opt]# docker run -d -p 8888:80 -v /opt/:/data registry.aliyuncs.com/openspug/spug
2c0f0f3911a38f3e152d6a82cb5b725e4e7147d7a3528720041efc8f39585112
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/data/spug/spug_api\") set in config.json failed: no such file or directory".
```

**Comment by vapao** [comment]
问题已确认，临时可通过 `-w` 参数更改 `WORKDIR` 来解决例如： `docker run -d -w /data -v /opt:/data registry.aliyuncs.com/openspug/spug`

**Comment by ztommyc** [comment]
刚刚重新pull了镜像, 容器可以启动, 但是前台输入账号密码后无法登陆,  报:
Exception: (2002, "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)")

查看/opt/spug/spug/spug_api/logs/monitor.log 有报错(是否跟宿主机有安装mysql有关?):
```
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    main()
  File "manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/data/spug/spug_api/apps/monitor/management/commands/runmonitor.py", line 13, in handle
    s.run()
  File "/data/spug/spug_api/apps/monitor/scheduler.py", line 113, in run
    self._init()
  File "/data/spug/spug_api/apps/monitor/scheduler.py", line 102, in _init
    for item in Detection.objects.filter(is_active=True):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1131, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 179, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2)")
```

**Comment by ztommyc** [comment]
> @ztommyc 看起来是mysql没有正常启动，可否提供下 `/data/mysql/mysql.err` 这个日志文件的内容

```
2020-05-19 18:02:10 0 [Note] InnoDB: Using Linux native AIO
2020-05-19 18:02:10 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2020-05-19 18:02:10 0 [Note] InnoDB: Uses event mutexes
2020-05-19 18:02:10 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2020-05-19 18:02:10 0 [Note] InnoDB: Number of pools: 1
2020-05-19 18:02:10 0 [Note] InnoDB: Using SSE2 crc32 instructions
2020-05-19 18:02:10 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2020-05-19 18:02:10 0 [Note] InnoDB: Completed initialization of buffer pool
2020-05-19 18:02:10 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2020-05-19 18:02:11 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
2020-05-19 18:02:11 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2020-05-19 18:02:11 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2020-05-19 18:02:11 0 [ERROR] InnoDB: preallocating 12582912 bytes for file ./ibtmp1 failed with error 95
2020-05-19 18:02:11 0 [ERROR] InnoDB: Could not set the file size of './ibtmp1'. Probably out of disk space
2020-05-19 18:02:11 0 [ERROR] InnoDB: Unable to create the shared innodb_temporary
2020-05-19 18:02:11 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
2020-05-19 18:02:11 0 [Note] InnoDB: FTS optimize thread exiting.
2020-05-19 18:02:16 0 [Note] InnoDB: Starting shutdown...
2020-05-19 18:02:16 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2020-05-19 18:02:16 0 [ERROR] Plugin 'InnoDB' init function returned error.
2020-05-19 18:02:16 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2020-05-19 18:02:16 0 [Note] Plugin 'FEEDBACK' is disabled.
2020-05-19 18:02:16 0 [ERROR] Unknown/unsupported storage engine: InnoDB
2020-05-19 18:02:16 0 [ERROR] Aborting
```

**Comment by vapao** [comment]
看报错信息像是磁盘空间不足引起的

**Comment by vapao** [comment]
> 问题已确认，临时可通过 `-w` 参数更改 `WORKDIR` 来解决例如： `docker run -d -w /data -v /opt:/data registry.aliyuncs.com/openspug/spug` 稍后我们会更新镜像，感谢你的反馈。

这个问题已更新，可以更新新版的镜像。

**Comment by ztommyc** [comment]
> 看报错信息像是磁盘空间不足引起的

```
[me@tee-test02 ~]$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
/dev/xvda3                    18G   11G  6.6G  63% /
devtmpfs                     7.8G     0  7.8G   0% /dev
tmpfs                        7.7G  512K  7.7G   1% /dev/shm
tmpfs                        7.7G  8.7M  7.7G   1% /run
tmpfs                        7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/xvda1                   497M  106M  392M  22% /boot
tmpfs                        1.6G     0  1.6G   0% /run/user/0
/dev/mapper/esbout-esboutlv  286G   48G  224G  18% /opt
tmpfs                        1.6G     0  1.6G   0% /run/user/801

```

**Comment by zyupo** [comment]
问题是否已经得到解决？如果解决暂时先关闭issues @ztommyc

**Comment by vapao** [comment]
@ztommyc  最后你那问题解决了吗，有其他用户遇到了同样的问题。

**Comment by ztommyc** [comment]
> @ztommyc 最后你那问题解决了吗，有其他用户遇到了同样的问题。

没有啊, 我还以为只有我遇到了.

**Comment by ztommyc** [comment]
https://github.com/docker-library/mariadb/issues/138
https://superuser.com/questions/1267663/docker-mariadb-instance-not-starting-after-update
