### ISSUE TITLE
Docker 如何安装拓展模块？

### ISSUE THREAD

**Issue by ChoGathK** [openspug/spug#96]
进入容器后执行
$ cd /data/spug/spug_api
$ python3 -m venv venv
$ source venv/bin/activate
pip install -r requirements.txt -i https://pypi.doubanio.com/simple

提示异常：
Command "/data/spug/spug_api/venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-9qq99bq7/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-bhqoa3iq/install-record.txt --single-version-externally-managed --compile --install-headers /data/spug/spug_api/venv/include/site/python3.6/cryptography" failed with error code 1 in /tmp/pip-install-9qq99bq7/cryptography/

**Comment by ChoGathK** [comment]
使用拓展文档执行：
标准安装批量执行的任务卡住无法看到执行输出
批量执行功能需要启动额外服务，通过以下命令启动，以下操作命令基于 标准安装 文档的环境

$ cd /data/spug/spug_api
$ source venv/bin/activate
$ python manage.py runworker ssh_exec

异常：
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    main()
  File "manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/data/spug/spug_api/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/data/spug/spug_api/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/data/spug/spug_api/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/data/spug/spug_api/venv/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/data/spug/spug_api/venv/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'channels'

**Comment by vapao** [comment]
你那边使用的那种方式安装呢，建议你参考下 [官方文档](https://spug.dev)

**Comment by ChoGathK** [comment]
已通过安装最新版 2.3.0 解决
